Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("train.csv")

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

Since its a text Data and we cannot replace with any value so we are dropping the Null Data

In [5]:
df.shape

(20800, 5)

In [6]:
##Dropping null values as we have huge data and null values in this case cannot be fixed
df=df.dropna()

In [7]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [8]:
#Get all the independent features 
X=df.drop(['label'],axis=1)

In [9]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [10]:
y=df['label']

In [11]:
import tensorflow as tf

In [12]:
tf.__version__

'2.15.0'

In [13]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [14]:
#Vocabulary size
voc_size=5000

In [15]:
messages=X.copy()

In [16]:
messages.title[1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [17]:
messages.reset_index(inplace=True)

In [18]:
import nltk
import re
from nltk.corpus import stopwords

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anubh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [21]:
corpus=[]
for i in range(0, len(messages)):
    review=re.sub('[^A-Za-z]',' ',messages['title'][i])
    review=review.lower()
    review=review.split()
    
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [22]:
onehot_resp=[one_hot(words,voc_size) for words in corpus]

In [23]:
onehot_resp

[[2717, 2142, 3850, 675, 773, 1110, 1649, 4169, 2701, 1741],
 [4728, 551, 4050, 4783, 2240, 1827, 2859],
 [1029, 4477, 3129, 4535],
 [3481, 4226, 2407, 548, 1541, 3561],
 [4177, 2240, 4711, 2584, 3555, 3117, 2240, 3818, 645, 291],
 [2321,
  48,
  3902,
  4627,
  125,
  444,
  4609,
  1666,
  147,
  3441,
  4929,
  2927,
  4814,
  117,
  2859],
 [4955, 338, 4376, 4628, 710, 1651, 1591, 3511, 4992, 524, 831],
 [4914, 3577, 2866, 4866, 1382, 897, 444, 928, 4992, 524, 831],
 [2747, 4047, 1733, 726, 444, 2114, 759, 2410, 444, 2254],
 [705, 531, 3903, 3641, 4322, 28, 2174, 3596],
 [600, 1335, 982, 2524, 208, 4983, 3426, 843, 2053, 4213, 927],
 [548, 543, 773, 2114, 444, 1382],
 [2650, 1238, 3569, 4385, 3790, 450, 877, 4302, 1061],
 [3959, 3436, 3036, 3451, 4215, 4554, 287, 4992, 524, 831],
 [2417, 2115, 1296, 2772, 1495, 4992, 524, 831],
 [4281, 3199, 4888, 3443, 2031, 3664, 380, 3476, 2653, 2399],
 [4326, 1083, 551],
 [2512, 4759, 2607, 4766, 444, 3291, 1607, 2859],
 [3728, 2865, 4050, 4318

In [24]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [25]:
onehot_resp[1]

[4728, 551, 4050, 4783, 2240, 1827, 2859]

# Embedding Representation

In [26]:
#Do padding before Embedding
sent_len=20
embedded_docs=pad_sequences(onehot_resp,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0 ... 4169 2701 1741]
 [   0    0    0 ... 2240 1827 2859]
 [   0    0    0 ... 4477 3129 4535]
 ...
 [   0    0    0 ... 4992  524  831]
 [   0    0    0 ... 4492 4001 4933]
 [   0    0    0 ... 3975 2649 4801]]


In [27]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [28]:
len(embedded_docs),y.shape

(18285, (18285,))

In [29]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [30]:
print(X_final[0])

[   0    0    0    0    0    0    0    0    0    0 2717 2142 3850  675
  773 1110 1649 4169 2701 1741]


In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [32]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10


192/192 [==============================] - 8s 30ms/step - loss: 0.3361 - accuracy: 0.8523 - val_loss: 0.1959 - val_accuracy: 0.9188
Epoch 2/10
192/192 [==============================] - 5s 25ms/step - loss: 0.1382 - accuracy: 0.9471 - val_loss: 0.1945 - val_accuracy: 0.9234
Epoch 3/10
192/192 [==============================] - 4s 21ms/step - loss: 0.0906 - accuracy: 0.9680 - val_loss: 0.2107 - val_accuracy: 0.9210
Epoch 4/10
192/192 [==============================] - 5s 23ms/step - loss: 0.0546 - accuracy: 0.9807 - val_loss: 0.2621 - val_accuracy: 0.9170
Epoch 5/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0313 - accuracy: 0.9899 - val_loss: 0.3692 - val_accuracy: 0.9107
Epoch 6/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0175 - accuracy: 0.9942 - val_loss: 0.3918 - val_accuracy: 0.9120
Epoch 7/10
192/192 [==============================] - 4s 22ms/step - loss: 0.0074 - accuracy: 0.9980 - val_loss: 0.4036 - val_accuracy: 0.91

# Performance Metrics And Accuracy

In [33]:
y_pred=model.predict(X_test)

189/189 [==============================] - 2s 5ms/step


In [34]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3153,  266],
       [ 280, 2336]], dtype=int64)

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9095277547638774

In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3419
           1       0.90      0.89      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035



# Adding DropOut

In [38]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [39]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 30ms/step - loss: 0.3425 - accuracy: 0.8357 - val_loss: 0.1996 - val_accuracy: 0.9193
Epoch 2/10
192/192 [==============================] - 5s 25ms/step - loss: 0.1506 - accuracy: 0.9408 - val_loss: 0.1947 - val_accuracy: 0.9163
Epoch 3/10
192/192 [==============================] - 5s 26ms/step - loss: 0.1109 - accuracy: 0.9593 - val_loss: 0.2092 - val_accuracy: 0.9122
Epoch 4/10
192/192 [==============================] - 5s 26ms/step - loss: 0.0933 - accuracy: 0.9658 - val_loss: 0.2227 - val_accuracy: 0.9168
Epoch 5/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0741 - accuracy: 0.9734 - val_loss: 0.2605 - val_accuracy: 0.9100
Epoch 6/10
192/192 [==============================] - 5s 23ms/step - loss: 0.0563 - accuracy: 0.9784 - val_loss: 0.3066 - val_accuracy: 0.9137
Epoch 7/10
192/192 [==============================] - 5s 26ms/step - loss: 0.0451 - accuracy: 0.9829 - val_loss: 0.3463 - val_accuracy: 0.9147

In [40]:
y_pred=model.predict(X_test)
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

189/189 [==============================] - 2s 6ms/step


array([[3137,  282],
       [ 270, 2346]], dtype=int64)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9085335542667772

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3419
           1       0.89      0.90      0.89      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035



In [43]:
df2=pd.read_csv("test.csv")

In [44]:
df2.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [45]:
messages2=df2.copy()

In [46]:
messages2.reset_index(inplace=True)
print(messages2.dtypes)


index      int64
id         int64
title     object
author    object
text      object
dtype: object


In [47]:
messages2.head()

index     id                                              title  \
0      0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1      1  20801  Russian warships ready to strike terrorists ne...   
2      2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3      3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4      4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [48]:
corpus=[]
review=[]
for i in range(0, len(messages2)):
    review=re.sub('[^A-Za-z]',' ',str(messages2['title'][i]))
    review=review.lower()
    review=review.split()
    
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [49]:
corpus[1]

'russian warship readi strike terrorist near aleppo'

In [50]:
onehot_resp=[]
onehot_resp=[one_hot(words,voc_size) for words in corpus]

In [51]:
onehot_resp[1]

[600, 1189, 2511, 3808, 3577, 1116, 3259]

In [52]:
#Do padding before Embedding
sent_len=20
embedded_docs=pad_sequences(onehot_resp,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0 ... 4992  524  831]
 [   0    0    0 ... 3577 1116 3259]
 [   0    0    0 ... 2774 3523 2213]
 ...
 [   0    0    0 ... 4992  524  831]
 [   0    0    0 ...  600 3700 1431]
 [   0    0    0 ... 4992  524  831]]


In [53]:
import numpy as np
X_test=np.array(embedded_docs)

In [54]:
y_pred=model.predict(X_test)
print(y_pred)
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

163/163 [==============================] - 1s 5ms/step
[[5.8800942e-06]
 [9.9824363e-01]
 [4.1007850e-02]
 ...
 [1.4719645e-06]
 [9.7655940e-01]
 [1.9908507e-06]]


In [55]:
predict_df=pd.DataFrame(y_pred,columns=['label'])

In [56]:
fake_out=pd.concat([df2['id'],predict_df],axis=1)

In [57]:
fake_out.to_csv("fake_out.csv",index=False)